spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: info
    password: password
    url: jdbc:mariadb://localhost:3306/icb
  devtools:
    add-properties: true

jwt:
  issuer: "i1nfo"
  public-key-path: ecc-public-key.pem
  private-key-path: ecc-private-key.pem
  expires-time: 1800
  update-time: 900

icb:
  admin:
    username: root
    password: password