server:
  shutdown: graceful
  port: 8080

spring:
  jackson:
    default-property-inclusion: non_null # exclude null value
  devtools:
    add-properties: false

mybatis-plus:
  configuration:
    default-executor-type: reuse
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true

jwt:
  issuer: "i1nfo"
  public-key-path: ecc-public-key.pem
  private-key-path: ecc-private-key.pem
  expires-time: 21600 # unit: second
  update-time: 7200 # delta time from update time to expire time

ic:
  recaptcha:
    hostname: recaptcha.net
