spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: info
    password: password
    url: jdbc:mariadb://localhost:3306/icb
  devtools:
    add-properties: true

icb:
  hostname: localhost